name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer kivy kivymd

    - name: Install Java (required for Android)
      run: sudo apt-get update && sudo apt-get install -y openjdk-11-jdk unzip wget

    - name: Install Android SDK and Build Tools
      run: |
        mkdir -p $HOME/.buildozer/android
        cd $HOME/.buildozer/android
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/

        # Set environment variables
        echo "export ANDROID_HOME=$HOME/.buildozer/android" >> $GITHUB_ENV
        echo "export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$ANDROID_HOME/platform-tools:\$PATH" >> $GITHUB_ENV
        export ANDROID_HOME=$HOME/.buildozer/android
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

        # Install SDK packages including AIDL and build tools
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" \
                   "build-tools;36.1.0" \
                   "platforms;android-33" \
                   "extras;android;m2repository" \
                   "extras;google;m2repository" \
                   "cmdline-tools;latest"

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: myapp-apk
        path: bin/*.apk
